INSERT OR IGNORE INTO categories (name) VALUES
  ('Dining'),
  ('Entertainment'),
  ('Gifts'),
  ('Groceries'),
  ('Health'),
  ('Housing'),
  ('Income'),
  ('Miscellaneous'),
  ('Other'),
  ('Savings'),
  ('Shopping'),
  ('Subscriptions'),
  ('Transportation'),
  ('Travel'),
  ('Uncategorized');
